//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.01 at 08:28:22 PM YEKT 
//


package kte_labs_soap_web_service;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="newScheduleDto" type="{kte-labs-soap-web-service}newScheduleDto"/&gt;
 *         &lt;element name="doctor" type="{kte-labs-soap-web-service}doctor"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "newScheduleDto",
    "doctor"
})
@XmlRootElement(name = "getScheduleRequest")
public class GetScheduleRequest {

    @XmlElement(required = true)
    protected NewScheduleDto newScheduleDto;
    @XmlElement(required = true)
    protected Doctor doctor;

    /**
     * Gets the value of the newScheduleDto property.
     * 
     * @return
     *     possible object is
     *     {@link NewScheduleDto }
     *     
     */
    public NewScheduleDto getNewScheduleDto() {
        return newScheduleDto;
    }

    /**
     * Sets the value of the newScheduleDto property.
     * 
     * @param value
     *     allowed object is
     *     {@link NewScheduleDto }
     *     
     */
    public void setNewScheduleDto(NewScheduleDto value) {
        this.newScheduleDto = value;
    }

    /**
     * Gets the value of the doctor property.
     * 
     * @return
     *     possible object is
     *     {@link Doctor }
     *     
     */
    public Doctor getDoctor() {
        return doctor;
    }

    /**
     * Sets the value of the doctor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Doctor }
     *     
     */
    public void setDoctor(Doctor value) {
        this.doctor = value;
    }

}
