//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.01 at 08:28:22 PM YEKT 
//


package kte_labs_soap_web_service;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kte_labs_soap_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kte_labs_soap_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetScheduleResponse }
     * 
     */
    public GetScheduleResponse createGetScheduleResponse() {
        return new GetScheduleResponse();
    }

    /**
     * Create an instance of {@link Doctor }
     * 
     */
    public Doctor createDoctor() {
        return new Doctor();
    }

    /**
     * Create an instance of {@link NewScheduleDto }
     * 
     */
    public NewScheduleDto createNewScheduleDto() {
        return new NewScheduleDto();
    }

    /**
     * Create an instance of {@link GetScheduleRequest }
     * 
     */
    public GetScheduleRequest createGetScheduleRequest() {
        return new GetScheduleRequest();
    }

    /**
     * Create an instance of {@link GetScheduleResponse.Schedules }
     * 
     */
    public GetScheduleResponse.Schedules createGetScheduleResponseSchedules() {
        return new GetScheduleResponse.Schedules();
    }

    /**
     * Create an instance of {@link Schedule }
     * 
     */
    public Schedule createSchedule() {
        return new Schedule();
    }

    /**
     * Create an instance of {@link Patient }
     * 
     */
    public Patient createPatient() {
        return new Patient();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link Doctor.Comments }
     * 
     */
    public Doctor.Comments createDoctorComments() {
        return new Doctor.Comments();
    }

    /**
     * Create an instance of {@link NewScheduleDto.WorkDays }
     * 
     */
    public NewScheduleDto.WorkDays createNewScheduleDtoWorkDays() {
        return new NewScheduleDto.WorkDays();
    }

}
