//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.02 at 12:50:28 AM YEKT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "kte-labs-soap-web-service", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package kte_labs_soap_web_service;
